package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;

public class MenuController extends BorderPane implements Initializable{
	@FXML
	private Button btnToonOverzicht;
	@FXML
	private Button btnSpeel;
	@FXML
	private Label loginMessageLabel;
	@FXML
	private Button btnExit;
	@FXML
	private ImageView background;

	public Button getBtnExit() {
		return btnExit;
	}
	
	public MenuController() {
		buildGui();
		
	}
	
	@FXML
	public void btnSpeelOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void btnToonOverzichtOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void btnExitOnAction(ActionEvent event) {
		
	}

	public Button getBtnToonOverzicht() {
		return btnToonOverzicht;
	}

	public Button getBtnSpeel() {
		return btnSpeel;
	}
	
	public void buildGui() {

		try {
			FXMLLoader loader = new FXMLLoader(this.getClass().getResource("menu.fxml"));
			loader.setRoot(this);
			loader.setController(this);
			loader.load();
		} catch (IOException e) {
			e.printStackTrace();
			System.err.println(e.getMessage());
			Platform.exit();
		}
	}

	@Override
	public void initialize(URL url, ResourceBundle rb) {
		// TODO Auto-generated method stub
		
	}
}
